sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kacperkwiatkowski/frontend-tweet -f Dockerfile.local .

script:
  - docker run -e CI=true kacperkwiatkowski/frontend-tweet npm run test

after_success:
  - docker build -t kacperkwiatkowski/frontend-tweet ./Dockerfile
  - docker build -t kacperkwiatkowski/nginx-tweet ./nginx
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kacperkwiatkowski/frontend-tweet
  - docker push kacperkwiatkowski/nginx-tweet

# deploy:
#   provider: elasticbeanstalk
#   region: eu-central-1
#   app: tweet-app-ui-eb
#   env: Tweetappuieb-env
#   bucket_name: elasticbeanstalk-eu-central-1-195077249767
#   bucket_path: tweet-app-bucket
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY