sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kacperkwiatkowski/frontend-tweet -f Dockerfile.local .

script:
  - docker run -e CI=true kacperkwiatkowski/frontend-tweet npm run test

after_success:
  - docker build -t kacperkwiatkowski/frontend-tweet ./Dockerfile
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kacperkwiatkowski/frontend-tweet