sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kacperkwiatkowski/frontend-tweet -f Dockerfile .

script:
  - docker run -e CI=true kacperkwiatkowski/frontend-tweet npm run test