sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kacperKwiatkowski/frontend-tweet -f

script:
  - docker run -e CI=true kacperKwiatkowski/frontend-tweet npm run test