version: '3.9'

networks:
  shared-net:
    driver: bridge

services:

  frontend-tweet:
    image: frontend-tweet
    container_name: frontend-tweet
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always