version: '3.9'

services:

  frontend-tweet:
    image: frontend-tweet
    container_name: frontend-tweet
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    networks:
      - nginx-network

  nginx-tweet:
    image: nginx-tweet
    container_name: nginx-tweet
    hostname: nginx-tweet
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend-tweet
    networks:
      - nginx-network
  
networks:
  nginx-network:
    driver: bridge