version: '3.9'

services:

  frontend-tweet:
    image: frontend-tweet
    container_name: frontend-tweet
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app